### ISSUE TITLE
NOT WORKING

### ISSUE THREAD

**Issue by NormTurtle** [FluxxField/bionic-reading.nvim#34]
> hey , im Omaru from reddit

Plugin  is not working for me 
idk how to really `debug` :(  <- please teach me

`minimal.config`
```lua
vim.opt.number = true
local lazypath = vim.fn.stdpath 'data' .. '/lazy/lazy.nvim'
if not vim.loop.fs_stat(lazypath) then
vim.fn.system {
	'git',
	'clone',
	'--filter=blob:none',
	'https://github.com/folke/lazy.nvim.git',
	'--branch=stable', -- latest stable release
	lazypath, } end
vim.opt.rtp:prepend(lazypath)
require('lazy').setup({
{
  'FluxxField/bionic-reading.nvim',
  config = function()
    require('bionic-reading').setup()
  end,
},
  }, {})
```

video demonstration : 
https://github.com/FluxxField/bionic-reading.nvim/assets/108952834/65babc81-649d-44e0-9d6b-5ad750e08472

### INFO
- OS : WIN 11
- nvim -v : 0.9.1
- FONT : [Delugia](https://github.com/adam7/delugia-code/)
- what else do i need to tell?

**Comment by NormTurtle** [comment]
and what is trying to say by this?
![image](https://github.com/FluxxField/bionic-reading.nvim/assets/108952834/15103bf3-663b-40d2-b0ad-2d99265f4f02)

**Comment by FluxxField** [comment]
> and what is trying to say by this? ![image](https://user-images.githubusercontent.com/108952834/242985347-15103bf3-663b-40d2-b0ad-2d99265f4f02.png)

You can set what file types you would like bionic-reader to auto run on. The default being just text.

When you run `BRToggle` on a file type that is not in your config, you are prompted, asking if you would like to highlight the current file. Thus, allowing you to highlight any file type on a per session bases

**Comment by FluxxField** [comment]
@NormTurtle Could you pull down the latest changes. Then could you tweak your configs the following

```lua
config = function()
  require('bionic-reading').setup({
    hl_group_value = {
      bg = "red",
      fg = "blue",
      bold = true,
    },
  })
end,
```

This will overwrite the default `hl_group_value`. Then, when you call `BRToggle`, the text should be blue with a red background. This will tell us if you have bold text enabled in your editor

**Comment by NormTurtle** [comment]
complete
